// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lorenzo/btcstaking/v1/event.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// BTC staking creation event
type EventBTCStakingCreated struct {
	Record *BTCStakingRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
}

func (m *EventBTCStakingCreated) Reset()         { *m = EventBTCStakingCreated{} }
func (m *EventBTCStakingCreated) String() string { return proto.CompactTextString(m) }
func (*EventBTCStakingCreated) ProtoMessage()    {}
func (*EventBTCStakingCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a42123e8d61ab98, []int{0}
}
func (m *EventBTCStakingCreated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBTCStakingCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBTCStakingCreated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBTCStakingCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBTCStakingCreated.Merge(m, src)
}
func (m *EventBTCStakingCreated) XXX_Size() int {
	return m.Size()
}
func (m *EventBTCStakingCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBTCStakingCreated.DiscardUnknown(m)
}

var xxx_messageInfo_EventBTCStakingCreated proto.InternalMessageInfo

func (m *EventBTCStakingCreated) GetRecord() *BTCStakingRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

// BTCB staking creation event
type EventBTCBStakingCreated struct {
	Record *BTCBStakingRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
}

func (m *EventBTCBStakingCreated) Reset()         { *m = EventBTCBStakingCreated{} }
func (m *EventBTCBStakingCreated) String() string { return proto.CompactTextString(m) }
func (*EventBTCBStakingCreated) ProtoMessage()    {}
func (*EventBTCBStakingCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a42123e8d61ab98, []int{1}
}
func (m *EventBTCBStakingCreated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBTCBStakingCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBTCBStakingCreated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBTCBStakingCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBTCBStakingCreated.Merge(m, src)
}
func (m *EventBTCBStakingCreated) XXX_Size() int {
	return m.Size()
}
func (m *EventBTCBStakingCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBTCBStakingCreated.DiscardUnknown(m)
}

var xxx_messageInfo_EventBTCBStakingCreated proto.InternalMessageInfo

func (m *EventBTCBStakingCreated) GetRecord() *BTCBStakingRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

type EventBurnCreated struct {
	Signer           string     `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	BtcTargetAddress string     `protobuf:"bytes,2,opt,name=btc_target_address,json=btcTargetAddress,proto3" json:"btc_target_address,omitempty"`
	Amount           types.Coin `protobuf:"bytes,3,opt,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
}

func (m *EventBurnCreated) Reset()         { *m = EventBurnCreated{} }
func (m *EventBurnCreated) String() string { return proto.CompactTextString(m) }
func (*EventBurnCreated) ProtoMessage()    {}
func (*EventBurnCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a42123e8d61ab98, []int{2}
}
func (m *EventBurnCreated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBurnCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBurnCreated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBurnCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBurnCreated.Merge(m, src)
}
func (m *EventBurnCreated) XXX_Size() int {
	return m.Size()
}
func (m *EventBurnCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBurnCreated.DiscardUnknown(m)
}

var xxx_messageInfo_EventBurnCreated proto.InternalMessageInfo

func (m *EventBurnCreated) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *EventBurnCreated) GetBtcTargetAddress() string {
	if m != nil {
		return m.BtcTargetAddress
	}
	return ""
}

func (m *EventBurnCreated) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

type EventMintStBTC struct {
	CosmosAddress string                                 `protobuf:"bytes,1,opt,name=cosmos_address,json=cosmosAddress,proto3" json:"cosmos_address,omitempty"`
	EthAddress    string                                 `protobuf:"bytes,2,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"`
	Amount        github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount"`
}

func (m *EventMintStBTC) Reset()         { *m = EventMintStBTC{} }
func (m *EventMintStBTC) String() string { return proto.CompactTextString(m) }
func (*EventMintStBTC) ProtoMessage()    {}
func (*EventMintStBTC) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a42123e8d61ab98, []int{3}
}
func (m *EventMintStBTC) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventMintStBTC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventMintStBTC.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventMintStBTC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMintStBTC.Merge(m, src)
}
func (m *EventMintStBTC) XXX_Size() int {
	return m.Size()
}
func (m *EventMintStBTC) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMintStBTC.DiscardUnknown(m)
}

var xxx_messageInfo_EventMintStBTC proto.InternalMessageInfo

func (m *EventMintStBTC) GetCosmosAddress() string {
	if m != nil {
		return m.CosmosAddress
	}
	return ""
}

func (m *EventMintStBTC) GetEthAddress() string {
	if m != nil {
		return m.EthAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*EventBTCStakingCreated)(nil), "lorenzo.btcstaking.v1.EventBTCStakingCreated")
	proto.RegisterType((*EventBTCBStakingCreated)(nil), "lorenzo.btcstaking.v1.EventBTCBStakingCreated")
	proto.RegisterType((*EventBurnCreated)(nil), "lorenzo.btcstaking.v1.EventBurnCreated")
	proto.RegisterType((*EventMintStBTC)(nil), "lorenzo.btcstaking.v1.EventMintStBTC")
}

func init() { proto.RegisterFile("lorenzo/btcstaking/v1/event.proto", fileDescriptor_3a42123e8d61ab98) }

var fileDescriptor_3a42123e8d61ab98 = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0x13, 0x85, 0xc0, 0xce, 0xe2, 0xb2, 0x04, 0x5d, 0xeb, 0x1e, 0x12, 0x2d, 0xa8, 0x45,
	0xdc, 0x19, 0x63, 0x4f, 0x9e, 0xd4, 0x14, 0x05, 0x41, 0x41, 0xd2, 0x5e, 0xd4, 0x43, 0x49, 0x26,
	0x43, 0x1a, 0xda, 0xce, 0x94, 0x99, 0xd7, 0xa0, 0x7e, 0x0a, 0x3f, 0x82, 0x67, 0xbf, 0x83, 0xf7,
	0x1e, 0x7b, 0x14, 0x0f, 0x55, 0xda, 0x2f, 0x22, 0x99, 0x99, 0xd8, 0x5a, 0x2a, 0xec, 0xa9, 0xaf,
	0x6f, 0xfe, 0xef, 0x3f, 0xbf, 0xc9, 0xff, 0xa1, 0x3b, 0x13, 0x21, 0x19, 0xff, 0x2c, 0x48, 0x06,
	0x54, 0x41, 0x3a, 0x2e, 0x79, 0x41, 0xaa, 0x88, 0xb0, 0x8a, 0x71, 0xc0, 0x33, 0x29, 0x40, 0xf8,
	0x37, 0xac, 0x04, 0x6f, 0x25, 0xb8, 0x8a, 0xce, 0x03, 0x2a, 0xd4, 0x54, 0x28, 0x92, 0xa5, 0x8a,
	0x91, 0x2a, 0xca, 0x18, 0xa4, 0x11, 0xa1, 0xa2, 0xe4, 0x66, 0xec, 0xfc, 0x7a, 0x21, 0x0a, 0xa1,
	0x4b, 0x52, 0x57, 0xb6, 0xfb, 0xe0, 0xf0, 0x7d, 0xb6, 0x1c, 0x4a, 0x46, 0x85, 0xcc, 0x8d, 0xb6,
	0xfd, 0x0e, 0x9d, 0xbd, 0xa8, 0x39, 0xe2, 0x41, 0xaf, 0x6f, 0xce, 0x7b, 0x92, 0xa5, 0xc0, 0x72,
	0xff, 0x29, 0xf2, 0x8c, 0xb2, 0xe5, 0xde, 0x76, 0x3b, 0xc7, 0x8f, 0xef, 0xe3, 0x83, 0x8c, 0x78,
	0x3b, 0x99, 0x68, 0x79, 0x62, 0xc7, 0xda, 0x1f, 0xd0, 0xcd, 0xc6, 0x3a, 0xde, 0xf3, 0x7e, 0xb6,
	0xe7, 0xdd, 0xf9, 0xbf, 0x77, 0x7c, 0xd8, 0xfc, 0xbb, 0x8b, 0x4e, 0x8d, 0xfb, 0x5c, 0xf2, 0xc6,
	0xf6, 0x0c, 0x79, 0xaa, 0x2c, 0x38, 0x93, 0xda, 0xf6, 0x28, 0xb1, 0xff, 0xfc, 0x87, 0xc8, 0xcf,
	0x80, 0x0e, 0x21, 0x95, 0x05, 0x83, 0x61, 0x9a, 0xe7, 0x92, 0x29, 0xd5, 0xba, 0xa2, 0x35, 0xa7,
	0x19, 0xd0, 0x81, 0x3e, 0x78, 0x6e, 0xfa, 0x3e, 0x45, 0x5e, 0x3a, 0x15, 0x73, 0x0e, 0xad, 0xab,
	0x1a, 0xee, 0x16, 0x36, 0x29, 0xe0, 0x3a, 0x05, 0x6c, 0x53, 0xc0, 0x3d, 0x51, 0xf2, 0xf8, 0xd1,
	0x62, 0x15, 0x3a, 0xdf, 0x7e, 0x85, 0x9d, 0xa2, 0x84, 0xd1, 0x3c, 0xc3, 0x54, 0x4c, 0x89, 0x8d,
	0xcc, 0xfc, 0x5c, 0xa8, 0x7c, 0x4c, 0xe0, 0xd3, 0x8c, 0x29, 0x3d, 0xa0, 0x12, 0x6b, 0xdd, 0xfe,
	0xea, 0xa2, 0x13, 0xcd, 0xff, 0xa6, 0xe4, 0xd0, 0xaf, 0xbf, 0x91, 0x7f, 0x17, 0x9d, 0x98, 0xa1,
	0xbf, 0x84, 0xe6, 0x15, 0xd7, 0x4c, 0xb7, 0xc1, 0x0b, 0xd1, 0x31, 0x83, 0xd1, 0xde, 0x2b, 0x10,
	0x83, 0x51, 0x23, 0x78, 0xf9, 0x0f, 0xff, 0x51, 0x8c, 0x6b, 0xc8, 0x9f, 0xab, 0xf0, 0xde, 0x25,
	0x20, 0x5f, 0x71, 0x68, 0x10, 0xe3, 0xfe, 0x62, 0x1d, 0xb8, 0xcb, 0x75, 0xe0, 0xfe, 0x5e, 0x07,
	0xee, 0x97, 0x4d, 0xe0, 0x2c, 0x37, 0x81, 0xf3, 0x63, 0x13, 0x38, 0xef, 0x9f, 0xec, 0x38, 0xbd,
	0x36, 0xc1, 0x5d, 0xbc, 0xad, 0xd7, 0x89, 0x8a, 0x09, 0x69, 0x96, 0xaf, 0xea, 0x92, 0x8f, 0xbb,
	0x1b, 0xa8, 0x2f, 0xc8, 0x3c, 0xbd, 0x76, 0xdd, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x3a,
	0xd3, 0x2e, 0x14, 0x03, 0x00, 0x00,
}

func (m *EventBTCStakingCreated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBTCStakingCreated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBTCStakingCreated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Record != nil {
		{
			size, err := m.Record.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventBTCBStakingCreated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBTCBStakingCreated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBTCBStakingCreated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Record != nil {
		{
			size, err := m.Record.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventBurnCreated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBurnCreated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBurnCreated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.BtcTargetAddress) > 0 {
		i -= len(m.BtcTargetAddress)
		copy(dAtA[i:], m.BtcTargetAddress)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.BtcTargetAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventMintStBTC) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventMintStBTC) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventMintStBTC) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.EthAddress) > 0 {
		i -= len(m.EthAddress)
		copy(dAtA[i:], m.EthAddress)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.EthAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.CosmosAddress) > 0 {
		i -= len(m.CosmosAddress)
		copy(dAtA[i:], m.CosmosAddress)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.CosmosAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventBTCStakingCreated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Record != nil {
		l = m.Record.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *EventBTCBStakingCreated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Record != nil {
		l = m.Record.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *EventBurnCreated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.BtcTargetAddress)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func (m *EventMintStBTC) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CosmosAddress)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.EthAddress)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventBTCStakingCreated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBTCStakingCreated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBTCStakingCreated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Record", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Record == nil {
				m.Record = &BTCStakingRecord{}
			}
			if err := m.Record.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventBTCBStakingCreated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBTCBStakingCreated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBTCBStakingCreated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Record", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Record == nil {
				m.Record = &BTCBStakingRecord{}
			}
			if err := m.Record.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventBurnCreated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBurnCreated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBurnCreated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcTargetAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcTargetAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventMintStBTC) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventMintStBTC: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventMintStBTC: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosmosAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CosmosAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EthAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
