// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lorenzo/btcstaking/v1/event.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// BTC staking creation event
type EventBTCStakingCreated struct {
	Record *BTCStakingRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
}

func (m *EventBTCStakingCreated) Reset()         { *m = EventBTCStakingCreated{} }
func (m *EventBTCStakingCreated) String() string { return proto.CompactTextString(m) }
func (*EventBTCStakingCreated) ProtoMessage()    {}
func (*EventBTCStakingCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a42123e8d61ab98, []int{0}
}
func (m *EventBTCStakingCreated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBTCStakingCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBTCStakingCreated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBTCStakingCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBTCStakingCreated.Merge(m, src)
}
func (m *EventBTCStakingCreated) XXX_Size() int {
	return m.Size()
}
func (m *EventBTCStakingCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBTCStakingCreated.DiscardUnknown(m)
}

var xxx_messageInfo_EventBTCStakingCreated proto.InternalMessageInfo

func (m *EventBTCStakingCreated) GetRecord() *BTCStakingRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

type EventBurnCreated struct {
	BtcTargetAddress string `protobuf:"bytes,1,opt,name=btc_target_address,json=btcTargetAddress,proto3" json:"btc_target_address,omitempty"`
	AmountDenom      string `protobuf:"bytes,2,opt,name=amount_denom,json=amountDenom,proto3" json:"amount_denom,omitempty"`
	AmountValue      uint64 `protobuf:"varint,3,opt,name=amount_value,json=amountValue,proto3" json:"amount_value,omitempty"`
	FeeDenom         string `protobuf:"bytes,4,opt,name=fee_denom,json=feeDenom,proto3" json:"fee_denom,omitempty"`
	FeeValue         uint64 `protobuf:"varint,5,opt,name=fee_value,json=feeValue,proto3" json:"fee_value,omitempty"`
}

func (m *EventBurnCreated) Reset()         { *m = EventBurnCreated{} }
func (m *EventBurnCreated) String() string { return proto.CompactTextString(m) }
func (*EventBurnCreated) ProtoMessage()    {}
func (*EventBurnCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a42123e8d61ab98, []int{1}
}
func (m *EventBurnCreated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBurnCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBurnCreated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBurnCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBurnCreated.Merge(m, src)
}
func (m *EventBurnCreated) XXX_Size() int {
	return m.Size()
}
func (m *EventBurnCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBurnCreated.DiscardUnknown(m)
}

var xxx_messageInfo_EventBurnCreated proto.InternalMessageInfo

func (m *EventBurnCreated) GetBtcTargetAddress() string {
	if m != nil {
		return m.BtcTargetAddress
	}
	return ""
}

func (m *EventBurnCreated) GetAmountDenom() string {
	if m != nil {
		return m.AmountDenom
	}
	return ""
}

func (m *EventBurnCreated) GetAmountValue() uint64 {
	if m != nil {
		return m.AmountValue
	}
	return 0
}

func (m *EventBurnCreated) GetFeeDenom() string {
	if m != nil {
		return m.FeeDenom
	}
	return ""
}

func (m *EventBurnCreated) GetFeeValue() uint64 {
	if m != nil {
		return m.FeeValue
	}
	return 0
}

func init() {
	proto.RegisterType((*EventBTCStakingCreated)(nil), "lorenzo.btcstaking.v1.EventBTCStakingCreated")
	proto.RegisterType((*EventBurnCreated)(nil), "lorenzo.btcstaking.v1.EventBurnCreated")
}

func init() { proto.RegisterFile("lorenzo/btcstaking/v1/event.proto", fileDescriptor_3a42123e8d61ab98) }

var fileDescriptor_3a42123e8d61ab98 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4b, 0x02, 0x41,
	0x1c, 0xc5, 0x9d, 0x32, 0xc9, 0xb1, 0x83, 0x2c, 0x14, 0x52, 0x30, 0xa8, 0x97, 0x24, 0x6a, 0x16,
	0x0b, 0xba, 0x46, 0x5a, 0xb7, 0x0e, 0x62, 0x12, 0xd4, 0x65, 0x99, 0x9d, 0xfd, 0x6b, 0x92, 0xce,
	0xc8, 0xec, 0x7f, 0x97, 0xea, 0x53, 0xf4, 0x91, 0x3a, 0x76, 0xf4, 0xd8, 0x31, 0xf4, 0x8b, 0xc4,
	0xce, 0xac, 0xe8, 0xc1, 0xdb, 0xf0, 0xde, 0xfb, 0xbd, 0x3f, 0xbc, 0xa1, 0x8d, 0x89, 0x36, 0xa0,
	0x3e, 0xb5, 0x1f, 0xa2, 0x8c, 0x51, 0xbc, 0x8d, 0xd5, 0xc8, 0x4f, 0xdb, 0x3e, 0xa4, 0xa0, 0x90,
	0xcf, 0x8c, 0x46, 0xed, 0x1d, 0xe6, 0x11, 0xbe, 0x8e, 0xf0, 0xb4, 0x7d, 0x7c, 0xb6, 0x9d, 0xcc,
	0x9f, 0x81, 0x01, 0xa9, 0x4d, 0xe4, 0x2a, 0x9a, 0xcf, 0xf4, 0xe8, 0x3e, 0x6b, 0xec, 0x0c, 0xba,
	0x8f, 0xce, 0xef, 0x1a, 0x10, 0x08, 0x91, 0x77, 0x43, 0x4b, 0x2e, 0x59, 0x23, 0x75, 0xd2, 0xaa,
	0x5c, 0x9e, 0xf2, 0xad, 0xd7, 0xf8, 0x9a, 0xec, 0xdb, 0x78, 0x3f, 0xc7, 0x9a, 0xdf, 0x84, 0x56,
	0x5d, 0x77, 0x62, 0xd4, 0xaa, 0xf5, 0x9c, 0x7a, 0x21, 0xca, 0x00, 0x85, 0x19, 0x01, 0x06, 0x22,
	0x8a, 0x0c, 0xc4, 0xb1, 0xbd, 0x50, 0xee, 0x57, 0x43, 0x94, 0x03, 0x6b, 0xdc, 0x3a, 0xdd, 0x6b,
	0xd0, 0x03, 0x31, 0xd5, 0x89, 0xc2, 0x20, 0x02, 0xa5, 0xa7, 0xb5, 0x1d, 0x9b, 0xab, 0x38, 0xed,
	0x2e, 0x93, 0x36, 0x22, 0xa9, 0x98, 0x24, 0x50, 0xdb, 0xad, 0x93, 0x56, 0x71, 0x15, 0x79, 0xca,
	0x24, 0xef, 0x84, 0x96, 0x87, 0x00, 0x79, 0x45, 0xd1, 0x56, 0xec, 0x0f, 0x01, 0x1c, 0x9f, 0x9b,
	0x0e, 0xde, 0xb3, 0x70, 0x66, 0x5a, 0xb2, 0xd3, 0xfb, 0x59, 0x30, 0x32, 0x5f, 0x30, 0xf2, 0xb7,
	0x60, 0xe4, 0x6b, 0xc9, 0x0a, 0xf3, 0x25, 0x2b, 0xfc, 0x2e, 0x59, 0xe1, 0xe5, 0x7a, 0x34, 0xc6,
	0xd7, 0x24, 0xe4, 0x52, 0x4f, 0xfd, 0x07, 0xb7, 0xcb, 0x45, 0x2f, 0x5b, 0x54, 0xea, 0x89, 0xbf,
	0xda, 0xff, 0x7d, 0xf3, 0x07, 0xf0, 0x63, 0x06, 0x71, 0x58, 0xb2, 0xb3, 0x5f, 0xfd, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x2e, 0x78, 0xe8, 0x7c, 0xde, 0x01, 0x00, 0x00,
}

func (m *EventBTCStakingCreated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBTCStakingCreated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBTCStakingCreated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Record != nil {
		{
			size, err := m.Record.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventBurnCreated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBurnCreated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBurnCreated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FeeValue != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.FeeValue))
		i--
		dAtA[i] = 0x28
	}
	if len(m.FeeDenom) > 0 {
		i -= len(m.FeeDenom)
		copy(dAtA[i:], m.FeeDenom)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.FeeDenom)))
		i--
		dAtA[i] = 0x22
	}
	if m.AmountValue != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.AmountValue))
		i--
		dAtA[i] = 0x18
	}
	if len(m.AmountDenom) > 0 {
		i -= len(m.AmountDenom)
		copy(dAtA[i:], m.AmountDenom)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.AmountDenom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.BtcTargetAddress) > 0 {
		i -= len(m.BtcTargetAddress)
		copy(dAtA[i:], m.BtcTargetAddress)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.BtcTargetAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventBTCStakingCreated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Record != nil {
		l = m.Record.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *EventBurnCreated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BtcTargetAddress)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.AmountDenom)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.AmountValue != 0 {
		n += 1 + sovEvent(uint64(m.AmountValue))
	}
	l = len(m.FeeDenom)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.FeeValue != 0 {
		n += 1 + sovEvent(uint64(m.FeeValue))
	}
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventBTCStakingCreated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBTCStakingCreated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBTCStakingCreated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Record", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Record == nil {
				m.Record = &BTCStakingRecord{}
			}
			if err := m.Record.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventBurnCreated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBurnCreated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBurnCreated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcTargetAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcTargetAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AmountDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountValue", wireType)
			}
			m.AmountValue = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AmountValue |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeValue", wireType)
			}
			m.FeeValue = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeeValue |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
