// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lorenzo/bnblightclient/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// the stake plan hub contract address
	StakePlanHubAddress string `protobuf:"bytes,1,opt,name=stake_plan_hub_address,json=stakePlanHubAddress,proto3" json:"stake_plan_hub_address,omitempty"`
	// event_index defines index of generated the event in the contract
	EventIndices []string `protobuf:"bytes,2,rep,name=event_indices,json=eventIndices,proto3" json:"event_indices,omitempty"`
	// event_name defines the event name
	EventName string `protobuf:"bytes,3,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	// the maximum number of bnb block headers to retain
	RetainedBlocks uint64 `protobuf:"varint,4,opt,name=retained_blocks,json=retainedBlocks,proto3" json:"retained_blocks,omitempty"`
	// list of people who can upload bnb block header information
	AllowList []string `protobuf:"bytes,5,rep,name=allow_list,json=allowList,proto3" json:"allow_list,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_3608f71b6e08ae9c, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetStakePlanHubAddress() string {
	if m != nil {
		return m.StakePlanHubAddress
	}
	return ""
}

func (m *Params) GetEventIndices() []string {
	if m != nil {
		return m.EventIndices
	}
	return nil
}

func (m *Params) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *Params) GetRetainedBlocks() uint64 {
	if m != nil {
		return m.RetainedBlocks
	}
	return 0
}

func (m *Params) GetAllowList() []string {
	if m != nil {
		return m.AllowList
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "lorenzo.bnblightclient.v1.Params")
}

func init() {
	proto.RegisterFile("lorenzo/bnblightclient/v1/params.proto", fileDescriptor_3608f71b6e08ae9c)
}

var fileDescriptor_3608f71b6e08ae9c = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcd, 0x4a, 0x33, 0x31,
	0x18, 0x85, 0x9b, 0xaf, 0xfd, 0x0a, 0x13, 0xfc, 0x81, 0x51, 0x64, 0x14, 0x8c, 0x45, 0x41, 0xbb,
	0x71, 0x42, 0xe9, 0xae, 0x3b, 0xbb, 0x52, 0x28, 0x52, 0x8a, 0x2b, 0x37, 0x21, 0x99, 0x79, 0x99,
	0x86, 0x66, 0x92, 0x61, 0x92, 0xd6, 0x9f, 0xab, 0xf0, 0x12, 0xbc, 0x1c, 0x77, 0x76, 0xe9, 0x52,
	0xda, 0x8d, 0x97, 0x21, 0x93, 0xb1, 0x0b, 0xdd, 0x85, 0xe7, 0x9c, 0x9c, 0x17, 0x1e, 0x7c, 0xae,
	0x4c, 0x09, 0xfa, 0xd9, 0x50, 0xa1, 0x85, 0x92, 0xd9, 0xd4, 0x25, 0x4a, 0x82, 0x76, 0x74, 0xd1,
	0xa3, 0x05, 0x2f, 0x79, 0x6e, 0xe3, 0xa2, 0x34, 0xce, 0x84, 0x87, 0x3f, 0xbd, 0xf8, 0x77, 0x2f,
	0x5e, 0xf4, 0x8e, 0xf6, 0x33, 0x93, 0x19, 0xdf, 0xa2, 0xd5, 0xab, 0xfe, 0x70, 0xfa, 0x8e, 0x70,
	0x7b, 0xec, 0x17, 0xc2, 0x3e, 0x3e, 0xb0, 0x8e, 0xcf, 0x80, 0x15, 0x8a, 0x6b, 0x36, 0x9d, 0x0b,
	0xc6, 0xd3, 0xb4, 0x04, 0x6b, 0x23, 0xd4, 0x41, 0xdd, 0x60, 0xb2, 0xe7, 0xd3, 0xb1, 0xe2, 0xfa,
	0x7a, 0x2e, 0xae, 0xea, 0x28, 0x3c, 0xc3, 0xdb, 0xb0, 0x00, 0xed, 0x98, 0xd4, 0xa9, 0x4c, 0xc0,
	0x46, 0xff, 0x3a, 0xcd, 0x6e, 0x30, 0xd9, 0xf2, 0xf0, 0xa6, 0x66, 0xe1, 0x31, 0xc6, 0x75, 0x49,
	0xf3, 0x1c, 0xa2, 0xa6, 0x5f, 0x0b, 0x3c, 0xb9, 0xe5, 0x39, 0x84, 0x17, 0x78, 0xb7, 0x04, 0xc7,
	0xa5, 0x86, 0x94, 0x09, 0x65, 0x92, 0x99, 0x8d, 0x5a, 0x1d, 0xd4, 0x6d, 0x4d, 0x76, 0x36, 0x78,
	0xe8, 0x69, 0xb5, 0xc3, 0x95, 0x32, 0x0f, 0x4c, 0x49, 0xeb, 0xa2, 0xff, 0xfe, 0x52, 0xe0, 0xc9,
	0x48, 0x5a, 0x37, 0x68, 0x7d, 0xbd, 0x9e, 0xa0, 0xe1, 0xdd, 0xdb, 0x8a, 0xa0, 0xe5, 0x8a, 0xa0,
	0xcf, 0x15, 0x41, 0x2f, 0x6b, 0xd2, 0x58, 0xae, 0x49, 0xe3, 0x63, 0x4d, 0x1a, 0xf7, 0x83, 0x4c,
	0xba, 0xe9, 0x5c, 0xc4, 0x89, 0xc9, 0xe9, 0xa8, 0xf6, 0x74, 0x39, 0xae, 0x2c, 0x24, 0x46, 0xd1,
	0x8d, 0xe0, 0xc7, 0xbf, 0x8a, 0xdd, 0x53, 0x01, 0x56, 0xb4, 0xbd, 0xae, 0xfe, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x9c, 0xb8, 0x0a, 0x29, 0x89, 0x01, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.StakePlanHubAddress != that1.StakePlanHubAddress {
		return false
	}
	if len(this.EventIndices) != len(that1.EventIndices) {
		return false
	}
	for i := range this.EventIndices {
		if this.EventIndices[i] != that1.EventIndices[i] {
			return false
		}
	}
	if this.EventName != that1.EventName {
		return false
	}
	if this.RetainedBlocks != that1.RetainedBlocks {
		return false
	}
	if len(this.AllowList) != len(that1.AllowList) {
		return false
	}
	for i := range this.AllowList {
		if this.AllowList[i] != that1.AllowList[i] {
			return false
		}
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AllowList) > 0 {
		for iNdEx := len(m.AllowList) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowList[iNdEx])
			copy(dAtA[i:], m.AllowList[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.AllowList[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.RetainedBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RetainedBlocks))
		i--
		dAtA[i] = 0x20
	}
	if len(m.EventName) > 0 {
		i -= len(m.EventName)
		copy(dAtA[i:], m.EventName)
		i = encodeVarintParams(dAtA, i, uint64(len(m.EventName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.EventIndices) > 0 {
		for iNdEx := len(m.EventIndices) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.EventIndices[iNdEx])
			copy(dAtA[i:], m.EventIndices[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.EventIndices[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.StakePlanHubAddress) > 0 {
		i -= len(m.StakePlanHubAddress)
		copy(dAtA[i:], m.StakePlanHubAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.StakePlanHubAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.StakePlanHubAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if len(m.EventIndices) > 0 {
		for _, s := range m.EventIndices {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	l = len(m.EventName)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.RetainedBlocks != 0 {
		n += 1 + sovParams(uint64(m.RetainedBlocks))
	}
	if len(m.AllowList) > 0 {
		for _, s := range m.AllowList {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakePlanHubAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakePlanHubAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventIndices", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EventIndices = append(m.EventIndices, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EventName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetainedBlocks", wireType)
			}
			m.RetainedBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RetainedBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowList = append(m.AllowList, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
